### PR TITLE
Rebased the branch and made some changes based on the secret changes

### PR DESCRIPTION
**Pull request by ShubhamRwt**
### Type of change

- Refactoring
- Documentation

### Description

This PR fixes the javadocs and checstyle issues. It also makes sure that changes are done based on the secret changes made upstream

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by tinaselenge** [comment]
Thanks @ShubhamRwt but there still seem to be some conflicts.

**Comment by ShubhamRwt** [comment]
Hmm my branch seems to be up to date, I guess this might be happening since while rebasing their were some merge conflicts for which I had to make some extra commits and those are conflicting. For eg. changes made in the `KafkaReconciler`

**Comment by tinaselenge** [comment]
Hmm, perhaps I should rebase the branch first and then apply your changes on top? Otherwise, we can't merge the PR.

**Comment by ShubhamRwt** [comment]
Okay, but that would mean you will have to fix the secrets issue too while rebasing? I would say go for it. Once you have rebased, I will add up all the other changes .

**Pull request merged**
